import type { ColorTokens } from '../types'

export const defaultLightColors: ColorTokens = {
  primary: '#2563EB',
  primaryForeground: '#FFFFFF',
  secondary: '#F1F5F9',
  secondaryForeground: '#0F172A',
  background: '#FFFFFF',
  foreground: '#0F172A',
  card: '#FFFFFF',
  cardForeground: '#0F172A',
  border: '#E2E8F0',
  input: '#E2E8F0',
  muted: '#F1F5F9',
  mutedForeground: '#64748B',
  destructive: '#EF4444',
  destructiveForeground: '#FFFFFF',
  success: '#22C55E',
  successForeground: '#FFFFFF',
  warning: '#F59E0B',
  warningForeground: '#FFFFFF',
  ring: '#2563EB',
}

export const defaultDarkColors: ColorTokens = {
  primary: '#60A5FA',
  primaryForeground: '#1E1E1E',
  secondary: '#1E293B',
  secondaryForeground: '#F8FAFC',
  background: '#0F172A',
  foreground: '#F8FAFC',
  card: '#1E293B',
  cardForeground: '#F8FAFC',
  border: '#334155',
  input: '#334155',
  muted: '#1E293B',
  mutedForeground: '#94A3B8',
  destructive: '#F87171',
  destructiveForeground: '#1E1E1E',
  success: '#4ADE80',
  successForeground: '#1E1E1E',
  warning: '#FBBF24',
  warningForeground: '#1E1E1E',
  ring: '#60A5FA',
}
